replicatedhq/embedded-cluster-operator

.github/workflows/deploy-helm-production.yaml, .github/workflows/deploy-helm-staging.yaml
fix wrong username and password for production registry and attempt to use a different tag name to see if that solves the problem we are having when pushing it to staging:
```
https://registry.staging.replicated.com/v2/library/embedded-cluster-operator-image/manifests/0.0.4: 400 Bad Request
```
=> chore: fix wrong username and password + tag name change

api/v1beta1/installation_types.go, api/v1beta1/zz_generated.deepcopy.go, charts/embedded-cluster-operator/charts/crds/templates/resources.yaml, config/crd/bases/embeddedcluster.replicated.com_installations.yaml
today users can have one configuration provided through the kots application but they can also provide overrides through the command line when installing a cluster (--overrides flag). this commit adds a property to the crd so we can keep track of the overrides used at install time as well as the config embedded through the kots app.
this commit also moves from keeping the whole config obect to holds only its spec (we don't care about config status).
=> feat: allowing for config overrides storage

controllers/installation_controller.go
as we now can have multiple installation objects in the cluster (one for each installation/upgrade) we need to take the last reported node status into account otherwise we may generate multiple node added events.
we sort the installations by creation timestamp and reconcile only the newest one, node status is copied from the previous installations into the newest one before comparing if something has changed with regards to the nodes.
=> bug: reuse last reported node status

controllers/installation_controller.go, pkg/release/release.go
in we want to replace the official k0s binary with our own version now we can make the release to point to a different URL. this URL should point to the binary and the binary must be the same that has been embedded into the embedded-cluster version (sha256 must match).
relates to https://github.com/replicatedhq/embedded-cluster/pull/205
=> feat: release metadata can now point to a different k0s

controllers/installation_controller.go, pkg/release/release.go
handle 'v' prefixes in desired version
include entire URL in 'I couldn't find metadata' error messages
=> mark installation state as failed when unable to get metadata

controllers/installation_controller.go, pkg/metrics/metrics.go
this reporting was done in the installer (embedded-cluster) but since we have changed the upgrade approach to work through autopilot we needed to find a new place for it. we now report it through the operator as it is the one that starts and keeps track of upgrades.
=> feat: introducing upgrade metric reporting

controllers/installation_controller.go
in case of conflicts or problems when saving the installation object we may end up reporting the same event more than once. this commit moves the metrics sending logic to a place after the installation object is saved.
=> feat: notify node changes only at the end of reconcile

controllers/installation_controller.go
when we first create a new installation object its status is empty therefore it is different from the status after the first reconcile.
on this scenarios we don't want to report back to our metric system as an upgrade succeess.
=> feat: do not report upgrade during installation

controllers/installation_controller.go, pkg/release/release.go
`replicated.app/embedded-cluster-public-files` provides metadata and k0s binaries on a replicated-owned IP, which we should use instead of github IPs.
The k0s binary URL parameter is now redundant as the k0s binary can be downloaded from `replicated.app` directly - even if it is a patched build. An example [on staging](https://staging.replicated.app/embedded-cluster-public-files/k0s-binaries/v1.28.4%2Bk0s.0-ec.0) works now.
=> fetch metadata.json and k0s files from replicated.app

controllers/helm.go, controllers/helm_test.go, controllers/installation_controller.go, controllers/installation_controller_test.go
- we always want to surface errors from chart objects
- checking `ChartName` gives us `oci://some/uri` or `repo/releasename` which caused charts to never be "seen"
=> bug: installation object never gets set to Installed due to false positive chart drift check

charts/embedded-cluster-operator/templates/embedded-cluster-operator-deployment.yaml, controllers/installation_controller.go
when deciding to start or not an upgrade we should take into account what is the current embedded cluster we are running on. without this fix we end up starting a cluster upgrade when it is not necessary.
we were using the kubernetes version (as in `kubectl version`) to determine if an upgrade was necessary or not. it turns out that when installed with k0s version v1.29.1+k0s.1 the kubernetes version reported is v1.29.1+k0s (notice the missing .1 at the end). because of this the running verion was never equal to the desired version (v1.29.1+k0s.1 != v1.29.1+k0s).
now we take into account the actual embedded cluster version. we do so through an environment variable. this environment variable will change only when the new operator deployment takes place (add-on upgrade) and at that stage …
=> feat: take the embedded version cluster into account

charts/embedded-cluster-operator/templates/embedded-cluster-operator-secret-support-bundle.yaml, charts/embedded-cluster-operator/templates/embedded-cluster-operator-support-bundle.yaml, charts/embedded-cluster-operator/troubleshoot/cluster-support-bundle.yaml, charts/embedded-cluster-operator/troubleshoot/host-support-bundle.yaml
So far collects logs for all "default" pods, see list below. Kots pods are not collected as its log collection will be placed in the kots-helm repository. Implements only one analyser: checks if an Installation object with "Installed" state exists. The support bundle has its URI property pointing to itself here in the main branch.
Pod logs collected:
- Embedded Cluster Operator
- Calico
- CoreDNS
- Kube proxy
- Metrics server
- OpenEBS
=> feat: add a default cluster support bundle

charts/embedded-cluster-operator/charts/crds/templates/resources.yaml, config/crd/bases/embeddedcluster.replicated.com_installations.yaml, go.mod, go.sum
https://app.shortcut.com/replicated/story/101432/trigger-airgap-upgrade-from-kots
runs `make manifests` after updating `github.com/replicatedhq/embedded-cluster-kinds` to `v1.1.1`
=> make manifests for embeddedClusterMetadata field

controllers/installation_controller.go, go.mod
plan's id is used internally to verify if a given plan has already been executed or not. if we create two different plans with the same id autopilot does not seem to be running the second as it consider it already finished.
we now start to use a random id and use an annotation to keep track of the 1 to 1 mapping between installation and autopilot plan.
=> bug: stop using plan id to index autopilot plans

charts/embedded-cluster-operator/templates/embedded-cluster-operator-support-bundle.yaml
This PR adds the `embedded-cluster-operator.labels` to the support bundle configmap that is part of the Helm chart templates. These labels are already applied to all other resources, but were not for this configmap.
Example - with the following values:
```
global:
labels:
example.com/back-me-up: "true"
```
it renders:
```
apiVersion: v1
kind: ConfigMap
metadata:
name: embedded-cluster-cluster-support-bundle
labels:
troubleshoot.sh/kind: support-bundle
app.kubernetes.io/instance: release-name
app.kubernetes.io/managed-by: Helm
app.kubernetes.io/name: embedded-cluster-operator
example.com/back-me-up: "true"
helm.sh/chart: embedded-cluster-operator-0.0.0
data:
...
```
=> add eco labels to support bundle configmap

controllers/installation_controller.go
Creation timestamp is essentially a random order after a velero restore, resulting in possible cluster rollback
=> sort installations by name, not creation timestamp

charts/embedded-cluster-operator/charts/crds/templates/resources.yaml, config/crd/bases/embeddedcluster.replicated.com_installations.yaml, controllers/installation_controller.go, go.mod, go.sum
users can now provide a cluster config on a secret and point to the secret on the installation object. the content of the secret is used instead of the config present in the installation's spec.
=> feat: allow cluster config on a secret

charts/embedded-cluster-operator/templates/embedded-cluster-operator-clusterrole.yaml, controllers/installation_controller.go, go.mod, go.sum
- allow the operator to watch secrets.
- sends over a copy of installation when updating its status.
- disable old installations even on failure while reading config.
- bump embedded-cluster-kinds.
=> bug: fix various issues with the reconcile

pkg/artifacts/artifacts.go
This PR modifies the operator so that it can pull OCI artifacts with and without TLS. This complements changes in https://github.com/replicatedhq/embedded-cluster/pull/630
=> pull artifacts with and without tls

charts/embedded-cluster-operator/charts/crds/templates/resources.yaml, config/crd/bases/embeddedcluster.replicated.com_installations.yaml, go.mod, go.sum
bumps the `github.com/replicatedhq/embedded-cluster-kinds` import to v1.3.0 and re-generates the CRDs for the new `isHighAvailability` field in the Installation spec
=> update crds for isHighAvailability field

charts/embedded-cluster-operator/charts/crds/templates/resources.yaml, config/crd/bases/embeddedcluster.replicated.com_installations.yaml, go.mod, go.sum
re-generates CRDs based on https://github.com/replicatedhq/embedded-cluster-kinds/pull/37
=> rename high availability field in installation object

controllers/installation_controller.go, controllers/installation_controller_test.go, pkg/util/name.go
When a new node event is received create a new job that fetches host preflight results from the new node and stores the results JSON in configmap named `my-node-host-preflight-results` in a `results.json` key
=> feat: Store host preflight results in config map for new nodes

charts/embedded-cluster-operator/charts/crds/templates/resources.yaml, config/crd/patches/labels_in_installations.yaml
The `ec-install` value [is used](https://github.com/replicatedhq/embedded-cluster/blob/bf3f84af3af87eb31106ed2e521e471400d96436/pkg/addons/embeddedclusteroperator/embeddedclusteroperator.go#L205) for the installation CR. The CRD should use the same label so that the CR restores successfully.
=> Use ec-install label for installation crd

.github/workflows/deploy-helm-production.yaml, .github/workflows/deploy-helm-staging.yaml, .github/workflows/pull-request.yaml, Makefile, deploy/melange.tmpl.yaml
unify with https://github.com/replicatedhq/embedded-cluster repo
=> fix: unify chainguard tooling

pkg/charts/charts.go
The name of the chart in the CR on install
```
chartName: /var/lib/embedded-cluster/charts/docker-registry-2.2.3.tgz
```
The name of the chart in the CR after upgrade
```
chartName: var/lib/embedded-cluster/charts/docker-registry-2.2.3.tgz
```
=> fix: prevent chart from changing name on upgrade
